<h1 align="center">¡Abrir el notebook desde Colab!</h1>
<br>

<p align="center">
<a href="https://colab.research.google.com/github/martinezarraigadamaria/IntroProgramacionPythonFCE2023/blob/master/clases/IntroProgPython5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
</p>

# Temario

---

> Librerías: Qué son y cómo se usan. Ejemplos.

> Cálculos matriciales y entre arrays con Numpy.

# Librerías

Hasta ahora, hemos usado solamente funciones y estructuras disponibles en la instalación base de Python, pero una de las fortalezas del lenguaje es su comunidad y todo lo que ha creado para facilitar un montón de trabajo a lo largo del tiempo, gracias a las librerías creadas (y en proceso de creación).

Una ***librería*** o ***paquete*** es código organizado en un conjunto de funciones implementadas por otras personas que nos facilitan realizar tareas, principalmente porque no debemos volver a programar este código. 


## ¿Cómo Usamos una Librería?

Para utilizar cualquier librería primero debemos ***importarla***. Para ello, se usa la ***palabra clave*** **`import`**, pero hay muchas formas de emplearla. Sabiendo esto, una posibilidad es utilizar la siguiente sintaxis:

> **`import`** (nombre de la libreria) **`as`** (nombre abreviado)

De esta forma, estamos habilitando el uso de todo lo que contiene el paquete importado. El comando **`as`** nos permite indicar el nombre que le damos a la librería dentro de nuestro código.


In [1]:
# Importamos la librería math y usamos el alias m
import math as m

print('El seno de 0 es ', m.sin(0), 'y el coseno', m.cos(0))

El seno de 0 es  0.0 y el coseno 1.0


In [2]:
import math
print('El seno de 0 es ', math.sin(0), 'y el coseno', math.cos(0))

El seno de 0 es  0.0 y el coseno 1.0


Por otro lado, las librerías muchas veces están separadas en distintos **módulos**. Podemos pensar entonces que una librería es como un estante de libros, donde en cada libro se encuentran las funciones de un tema en común. Incluso un "libro" podría estar subdividido en "capítulos". Es decir, los distintos módulos de una librería podrían llegar a estar subdivididos en submódulos, y cada submódulo podría estar nuevamente subdividido, etc.

En el caso de que no querramos importar la librería completa, podemos importar sólo un módulo, de esta forma:

> **`from`** (nombre de la libreria) **`import`** (nombre de un módulo) **`as`** (nombre abreviado)


In [ ]:
#Importamos directamente las funciones que usaremos (separadas por comas)
from math import sin, cos 
#from math import *

print('El seno de 0 es ', sin(0), 'y el coseno', cos(0))

Análogamente a la importación anterior, se puede usar un punto para acceder a un módulo, como se muestra a continuación:

> **`import`** (nombre de la libreria)**.**(nombre de un módulo) **`as`** (nombre abreviado)

Una vez importada una librería, podremos utilizar las funciones definidas en ella. Para poder hacer uso y ejecutar una función que se encuentra en una librería, necesitamos especificarlo usando un punto entre el nombre de la librería (o su nombre abreviado) y la función. La sintaxis es la siguiente:

> (nombre de la libreria)**.**función*(argumentos)*

En el caso de importar una librería que se encuentre dividida en módulos, debemos especificar el módulo correspondiente a la función nuevamente con un punto:

> (nombre de la libreria)**.**(nombre del módulo)**.**función*(argumentos)*


In [3]:
# Podemos ver todo lo que tiene disponible la librería con la función dir
dir(m)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [4]:
# Podemos pedir las líneas de documentación de la función que deseemos
help(m.sin)

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).



### **Aclaraciones:**
- **No es obligatorio especificar un nombre abreviado con `as`**, podemos utilizar una librería con su nombre original, omitiendo este comando. Sin embargo, utilizar abreviaturas puede simplificar la legibilidad del código en algunos casos.
- Así como pueden importarse módulos de una librería, **también pueden importarse funciones sueltas**, según lo que necesitemos. **¡Pero cuidado!** Los nombres de funciones deben ser únicos. Si importan una función directamente, entonces no podrán definir su propia función con el mismo nombre.
- Es una **buena práctica** que todas las librerías se importen al principio del programa, o sea que las instrucciones de **`import`** se encuentren arriba de todo. Y es aún mejor práctica que los imports estén hechos en orden alfabético (aunque al principio sea mucho pedir).

A continuación veremos diversos ejemplos de librerías para conocer el potencial de estas herramientas y podamos aprender a utilizar otras librerías nuevas en el futuro, que se adapten a nuestras necesidades y problemáticas particulares.

Algunas librerías muy conocidas y utilizadas, especialmente en ciencia de datos, son:

*   [numpy](https://numpy.org/) (Cálculo matricial)
*   [pandas](https://pandas.pydata.org/) (Lectura y manipulación de datos)
*   [maplotlib](https://matplotlib.org/) (Gráficos)
*   [seaborn](https://seaborn.pydata.org/) (Gráficos)
*   [scipy](https://www.scipy.org/) (Ciencia de datos)
*   [scikit-learn](https://scikit-learn.org) (Machine Learning)


## Ejemplos de Librerías

A continuación se presentan un conjunto de ejemplos con diversas librerías. Cada una de ellas ofrece muchas más opciones y capacidades, pero la idea es que les ayude a tener un panorama del tipo de herramientas que existen, y que se animen a buscar nuevas librerías que solucionen sus problemas específicos.

Cabe destacar que algunas de estas librerías ya vienen incluídas con la instalación de Python, mientras que otras deben ser instaladas de forma independiente. En [este link](https://docs.python.org/3/library/) pueden investigar acerca de todas las librerías estándar que trae Python. Si cierta librería no se encuentra instalada en el sistema entonces el comando **`import`** para esa librería no funcionará con su instalación base de Python. 

**Notas:**

- Todas las librerías o paquetes cuentan con su **documentación**, la cual nos permite explorar los módulos que contiene y las funciones disponibles dentro de cada uno de ellos.
- **Recurrir a la documentación** es muy útil e importante a la hora de entender cómo usar las herramientas disponibles en una librería.

### 📌 [math](https://docs.python.org/3/library/math.html#module-math)

- *Compilado de funciones matemáticas básicas*

In [5]:
import math

x = 10.14 # float

print('Ceil de x', math.ceil(x))
print('Floor de x', math.floor(x))
print('Trunc de x', math.trunc(x))

Ceil de x 11
Floor de x 10
Trunc de x 10


In [6]:
x = -10.14

print('Ceil de x', math.ceil(x))
print('Floor de x', math.floor(x))
print('Trunc de x', math.trunc(x))

Ceil de x -10
Floor de x -11
Trunc de x -10


In [7]:
print(math.factorial(4)) # factorial(3) = 1 * 2 * 3

24


### 📌 [copy](https://docs.python.org/3/library/copy.html)

* *Copiado de estructuras de datos*

In [8]:
# Por defecto Python NO copia estructuras de datos para ahorrar memoria:
A = [1, 2, 3]
B = A
B += [4, 5, 6] # B = B + [4,5,6]

# No modificamos directamente A, sin embargo su valor cambió
# En este caso, 'B' es un nombre alternativo de 'A', no es una copia
print(A)
print(B)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [9]:
# Con .copy() realizamos una copia real

A = [1, 2, 3]
B = A.copy()
B += [4, 5, 6]

print(A)
print(B)

[1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [10]:
# Usando sólo .copy() no alcanza para que se copien las estructuras internas
# Esto se llama una copia 'superficial'
# solamente la capa 'externa' es la que se copia

A = [[1,2,3], [4,5,6], [7,8,9]]
B = A.copy()
B[0][0] = 999
B += [10, 11, 12]

print(A)
print(B)

[[999, 2, 3], [4, 5, 6], [7, 8, 9]]
[[999, 2, 3], [4, 5, 6], [7, 8, 9], 10, 11, 12]


In [11]:
# Con la librería copy y su función deepcopy() realizamos una copia real
# 'profunda' tal como queremos

import copy

A = [[1,2,3], [4,5,6], [7,8,9]]
B = copy.deepcopy(A)
B[0][0] = 999
B += [10, 11, 12]

# La lista A se mantiene intacta
print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[999, 2, 3], [4, 5, 6], [7, 8, 9], 10, 11, 12]


### 📌 [random](https://docs.python.org/3/library/random.html)

* *Generación aleatoria de números*

In [14]:
import random

opciones = ['Manzanas', 'Bananas', 'Naranjas', 'Uvas', 'Peras']
print(random.choice(opciones))

Naranjas


In [18]:
# La función shuffle reordena una lista y modifica el elemento que recibe como argumento!
random.shuffle(opciones)
print(opciones)

['Uvas', 'Peras', 'Manzanas', 'Bananas', 'Naranjas']


In [21]:
# Con sample podemos tomar muestras aleatorias de objetos de nuestra lista
print(random.sample(opciones, k=3))

['Bananas', 'Uvas', 'Peras']


In [24]:
# Entero aleatorio entre dos números (inclusive ambos)
print(random.randint( 10, 20 ))

# Decimal aleatorio entre [0.0, 1.0)
print(round(random.random(),3))

16
0.261


### 📌 [time](https://docs.python.org/3/library/time.html)

* *Funciones relacionadas al manejo del tiempo*

In [25]:
import time
# sleep le ordena a la computadora "dormir" por la cantidad de segundos que coloquemos como input.
print(1)
time.sleep(1)
print(2)
time.sleep(1)
print(3)
time.sleep(1)
print(4)
time.sleep(1)
print(5)
time.sleep(1)
print('Adiós!')

1
2
3
4
5
Adiós!


In [26]:
time.time()

1680727993.8610687

In [27]:
# time.time() pregunta la hora y podemos utilizarla
# para saber cuánto tardamos en ejecutar una función o bloque de código
# ¿Cómo muestra una fecha?

start = time.time()
print("Hola")
end = time.time()

print("Imprimir esto nos tomó", end - start, "segundos")

Hola
Imprimir esto nos tomó 0.00013136863708496094 segundos


### 📌 [NumPy](https://numpy.org/)
* *Álgebra Lineal y Cálculo*

NumPy permite crear vectores y matrices multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellos de forma muy eficiente.

El elemento básico sobre el que se opera en Numpy se lo denomina *array*. Un ***array*** en Numpy es lo que conocemos como vector o matriz y sus valores son listas con una restricción especial: que sus valores sean todos del mismo tipo.

Podemos resolver algunos ejercicios de álgebra lineal con esta librería.

In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 63.4 MB/s eta 0:00:0000:0100:01


In [2]:
import numpy as np
# La estructura básica de Numpy (matriz, vector o tensor) es el array.
A = np.array([
                [1,2,3],
                [4,5,6],
            ])

B = np.array([
                [1,2], 
                [4,5], 
                [7,8]
            ])

C = np.dot(A, B)

print('A =')
print(A)
print()
print('B =')
print(B)
print()
print('A*B =')
print(C)

A =
[[1 2 3]
 [4 5 6]]

B =
[[1 2]
 [4 5]
 [7 8]]

A*B =
[[30 36]
 [66 81]]


In [3]:
# Veamos la diferencia entre listas o arrays
# Suma o producto de listas concatena
a = [2, 4]
print("Para la lista a = [2, 4] ")
print("a + a:  ", a + a) # [2, 4, 2, 4]
print("a * 3:  ", a * 3) # [ 2, 4, 2, 4, 2, 4 ]
 
# Suma o producto de numpy arrays aplica la operación elemento a elemento
a = np.array(a)
print("\nPara el array a = [2, 4] ")
print("a + a:  ", a + a)
print("a * 3:  ", a * 3)


Para la lista a = [2, 4] 
a + a:   [2, 4, 2, 4]
a * 3:   [2, 4, 2, 4, 2, 4]

Para el array a = [2, 4] 
a + a:   [4 8]
a * 3:   [ 6 12]


In [4]:
a = [1,2,3]
b = [1,2]
print(a+b)

[1, 2, 3, 1, 2]


In [6]:
a = np.array([1,2,3])
b = np.array([1,2, 5])

#Qué sucede si queremos sumar dos arrays de diferente tamaño?
print("a + b:  ", a + b)

a + b:   [2 4 8]


In [7]:
# Tenemos 3 matrices y varias operaciones para realizar entre ellas.

A = np.array([
                [3, 0.],
                [-1, 2],
                [1, 1],
            ])

B = np.array([
                [4, -1.],
                [0, 2],
            ])

C = np.array([
                [1., 1, -1],
                [2, -1, 1],
            ])

# La multiplicación matricial requiere que usemos @ en vez de *

print(f"A * B =\n {A @ B}\n")
print(f"A * A^T =\n {A @ A.T}\n")
print(f"A^T * A =\n {A.T @ A}\n")
print(f"A + C^T =\n {A + C.T}\n")
print(f"2A =\n {2 * A}")

A * B =
 [[12. -3.]
 [-4.  5.]
 [ 4.  1.]]

A * A^T =
 [[ 9. -3.  3.]
 [-3.  5.  1.]
 [ 3.  1.  2.]]

A^T * A =
 [[11. -1.]
 [-1.  5.]]

A + C^T =
 [[4. 2.]
 [0. 1.]
 [0. 2.]]

2A =
 [[ 6.  0.]
 [-2.  4.]
 [ 2.  2.]]


In [9]:
print(A)
print()
print(A.T)

[[ 3.  0.]
 [-1.  2.]
 [ 1.  1.]]

[[ 3. -1.  1.]
 [ 0.  2.  1.]]


### 📌 [pandas](https://pandas.pydata.org/)
* *Análisis y manipulación de datos*

In [11]:
!pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 78.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 40.7 MB/s eta 0:00:00


In [12]:
# Importaciones pertinentes 
import pandas as pd

El conjunto de datos utilizado contiene información de referencia y de rendimiento de préstamos para 5,960 préstamos. El objetivo (BAD) es una variable binaria que indica si un solicitante finalmente incurrió en incumplimiento o en grave mora en alguna entidad bancaria. Y por muestreo rápido. 

Los datos son los siguientes:

- BAD: 1 = candidato con préstamo incumplido o con mora; 0 = candidato que paga su deuda y no tiene registro negativo

- LOAN: Monto de solicitud de préstamo

- MORTDUE: Monto adeudado de la hipoteca existente

- VALUE: Valor actual del bien o propiedad

- REASON: DebtCon = consolidación de la deuda; HomeImp = mejoras para el hogar

- JOB: Categorias ocupacionales o profesionales

- YOJ: Años en su trabajo actual

- DEROG: Número de informes derogados o cancelados importantes

- DELINQ: Número de lineas de crédito morosas

- CLAGE: Antiguedad de la linea de crédito más antigua en meses

- NINQ: Número de consultas crediticas recientes

- CLNO: Número de líneas de crédito

- DEBTINC: -

In [13]:
#Vamos a traer los datos que necesitamos para trabajar, mediante la lectura del archivo CSV (hmeq)
#Para ello podemos utilizar la función read_csv()

url = "https://raw.githubusercontent.com/martinezarraigadamaria/IntroProgramacionPythonFCE2023/main/datos/hmeq.csv"
df = pd.read_csv(url) #dataframe

In [15]:
df

BAD   LOAN  MORTDUE     VALUE   REASON     JOB   YOJ  DEROG  DELINQ   
0       1   1100  25860.0   39025.0  HomeImp   Other  10.5    0.0     0.0  \
1       1   1300  70053.0   68400.0  HomeImp   Other   7.0    0.0     2.0   
2       1   1500  13500.0   16700.0  HomeImp   Other   4.0    0.0     0.0   
3       1   1500      NaN       NaN      NaN     NaN   NaN    NaN     NaN   
4       0   1700  97800.0  112000.0  HomeImp  Office   3.0    0.0     0.0   
...   ...    ...      ...       ...      ...     ...   ...    ...     ...   
5955    0  88900  57264.0   90185.0  DebtCon   Other  16.0    0.0     0.0   
5956    0  89000  54576.0   92937.0  DebtCon   Other  16.0    0.0     0.0   
5957    0  89200  54045.0   92924.0  DebtCon   Other  15.0    0.0     0.0   
5958    0  89800  50370.0   91861.0  DebtCon   Other  14.0    0.0     0.0   
5959    0  89900  48811.0   88934.0  DebtCon   Other  15.0    0.0     0.0   

           CLAGE  NINQ  CLNO    DEBTINC  
0      94.366667   1.0   9.0        NaN  
1     121.833333   0.0  14.0        NaN  
2     149.466667   1.0  10.0        NaN  
3            NaN   NaN   NaN        NaN  
4      93.333333   0.0  14.0        NaN  
...          ...   ...   ...        ...  
5955  221.808718   0.0  16.0  36.112347  
5956  208.692070   0.0  15.0  35.859971  
5957  212.279697   0.0  15.0  35.556590  
5958  213.892709   0.0  16.0  34.340882  
5959  219.601002   0.0  16.0  34.571519  

[5960 rows x 13 columns]

In [16]:
# Cuántas filas y columnas tienen?
print(df.shape) 

(5960, 13)


In [19]:
# Ver primeras filas (por defecto mostrará las primeras 5 filas, usando .head(n) veremos las primeras n filas)
df.head(10)

BAD  LOAN  MORTDUE     VALUE   REASON     JOB   YOJ  DEROG  DELINQ   
0    1  1100  25860.0   39025.0  HomeImp   Other  10.5    0.0     0.0  \
1    1  1300  70053.0   68400.0  HomeImp   Other   7.0    0.0     2.0   
2    1  1500  13500.0   16700.0  HomeImp   Other   4.0    0.0     0.0   
3    1  1500      NaN       NaN      NaN     NaN   NaN    NaN     NaN   
4    0  1700  97800.0  112000.0  HomeImp  Office   3.0    0.0     0.0   
5    1  1700  30548.0   40320.0  HomeImp   Other   9.0    0.0     0.0   
6    1  1800  48649.0   57037.0  HomeImp   Other   5.0    3.0     2.0   
7    1  1800  28502.0   43034.0  HomeImp   Other  11.0    0.0     0.0   
8    1  2000  32700.0   46740.0  HomeImp   Other   3.0    0.0     2.0   
9    1  2000      NaN   62250.0  HomeImp   Sales  16.0    0.0     0.0   

        CLAGE  NINQ  CLNO    DEBTINC  
0   94.366667   1.0   9.0        NaN  
1  121.833333   0.0  14.0        NaN  
2  149.466667   1.0  10.0        NaN  
3         NaN   NaN   NaN        NaN  
4   93.333333   0.0  14.0        NaN  
5  101.466002   1.0   8.0  37.113614  
6   77.100000   1.0  17.0        NaN  
7   88.766030   0.0   8.0  36.884894  
8  216.933333   1.0  12.0        NaN  
9  115.800000   0.0  13.0        NaN

In [21]:
# Ver últimas filas
df.tail(3)

BAD   LOAN  MORTDUE    VALUE   REASON    JOB   YOJ  DEROG  DELINQ   
5957    0  89200  54045.0  92924.0  DebtCon  Other  15.0    0.0     0.0  \
5958    0  89800  50370.0  91861.0  DebtCon  Other  14.0    0.0     0.0   
5959    0  89900  48811.0  88934.0  DebtCon  Other  15.0    0.0     0.0   

           CLAGE  NINQ  CLNO    DEBTINC  
5957  212.279697   0.0  15.0  35.556590  
5958  213.892709   0.0  16.0  34.340882  
5959  219.601002   0.0  16.0  34.571519

In [22]:
# ¿Qué tipo de objeto es?
print('Mis datos:',type(df))

Mis datos: <class 'pandas.core.frame.DataFrame'>


In [23]:
# Seleccionar las columnas
print(df.columns)

Index(['BAD', 'LOAN', 'MORTDUE', 'VALUE', 'REASON', 'JOB', 'YOJ', 'DEROG',
       'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC'],
      dtype='object')


In [24]:
# Seleccionar columnas por nombre
df['JOB']

0        Other
1        Other
2        Other
3          NaN
4       Office
         ...  
5955     Other
5956     Other
5957     Other
5958     Other
5959     Other
Name: JOB, Length: 5960, dtype: object

In [26]:
# Seleccionar columnas por indice
df[df.columns[0]]

0       1
1       1
2       1
3       1
4       0
       ..
5955    0
5956    0
5957    0
5958    0
5959    0
Name: BAD, Length: 5960, dtype: int64

In [27]:
# Seleccionar filas por condición

nombre_columna = "BAD"
condicion = 0
df[nombre_columna]==condicion

0       False
1       False
2       False
3       False
4        True
        ...  
5955     True
5956     True
5957     True
5958     True
5959     True
Name: BAD, Length: 5960, dtype: bool

### 📌 [Matplotlib](https://matplotlib.org)
* *Visualización de datos*

In [28]:
!pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 74.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 19.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 90.2 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 73.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 41.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 88.0 MB/s eta 0:00:00


In [29]:
# Ejemplo obtenido de la documentación de matplotlib para darse una idea del
# uso de esta herramienta

import matplotlib.pyplot as plt

In [30]:
#Gráficos simples
plt.plot(df['LOAN'])

In [32]:
df.columns

Index(['BAD', 'LOAN', 'MORTDUE', 'VALUE', 'REASON', 'JOB', 'YOJ', 'DEROG',
       'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC'],
      dtype='object')

In [33]:
# Utilizando el módulo matplotlib.pyplot
df.plot.scatter("YOJ", "VALUE")

<Axes: xlabel='YOJ', ylabel='VALUE'>

# Paréntesis: *f-strings*

Como habrán notado, existen formas de "*incrustar*" variables en texto de una manera muy amigable gracias a las *formatted strings literals* (más conocidas por su nombre artístico *f-strings*).

Esto nos salva de concatenar strings y hace mucho más legible el texto que querramos crear. Por ejemplo, nos hacen muy sencillo presentar un número como un porcentaje.



In [36]:
edad = 25

print("La edad de Roberto es ", edad)
print(f"La edad de Roberto es {edad}")

La edad de Roberto es  25
La edad de Roberto es 25


In [39]:
x = 0.253246

print(f"El porcentaje es {x:%}")
print(f"El porcentaje a dos decimales es {x:.2%}")
print(f"En porcentaje a tres decimales es {x:.3%}")

El porcentaje es 25.324600%
El porcentaje a dos decimales es 25.32%
En porcentaje a tres decimales es 25.325%


In [42]:
cantante = "La Mona Jimenez"
numero = 1000000

print(f"{cantante} sorteó ${numero} en su último recital.")
print(cantante , "sorteó $", numero, "en su último recital.")

La Mona Jimenez sorteó $1000000 en su último recital.
La Mona Jimenez sorteó $ 1000000 en su último recital.


In [43]:
diccionario = {
    "cantante": "La Mona Jimenez",
    "numero": 3000000,
}

print(f"{diccionario['cantante']} sorteó ${diccionario['numero']} en su último recital.")

La Mona Jimenez sorteó $3000000 en su último recital.


En [esta documentación](https://docs.python.org/3/library/string.html#formatstrings) encontrarán más información al respecto. Además, dentro del tutorial de Python, pueden revisar [esta sección](https://docs.python.org/3/tutorial/inputoutput.html).